### ISSUE TITLE
Game ending on start

### ISSUE THREAD

**Issue by AlexBartles** [steve4744/TNTRun#110]
I am using TnTRun_reloaded v6.8.7 on my Spigot 1.8.9 server and whenever the game starts, the game ends immediately and the 2nd player wins. Please help!

**Comment by AlexBartles** [comment]
> This is almost always due to either the arena bounds not including the whole of the arena, or the lose level set at the wrong height. Resetting the bounds and lose level should fix the problem.

I have tried both of those but it is still instantly ending.

**Comment by steve4744** [comment]
Can you post the contents of the arena config file  - maybe there's something wrong in there.

**Comment by AlexBartles** [comment]
> Can you post the contents of the arena config file - maybe there's something wrong in there.

Yeah sure!

Link: https://pastebin.com/6Cdrp1HP

Password: DF9vkAKbZ4

**Comment by steve4744** [comment]
Thanks for that. 
In this version of the plugin, when you select the 2 points for the lose level, they should be be on the same Y level (so you're selecting a 2D rectangle rather than a 3D cuboid). In your config file, the Y coordinate of your 2 lose level points are Y=137 and Y=185  - they should both be the same but the plugin will use the highest which is Y=185.

The Y coordinate of your spawn point is 154, so when the game starts your players are all below Y=185 (the lose level) so the game ends.

So either redo the lose level setting both points on the same Y coordinate, or edit the arena config and change the lose level P2 Y value to 137 (or even 138 as the lower bound of the arena is 137, and the lose level should be inside the arena bounds).

Not sure why the lose level was originally set using 2 points, but the newer versions of the plugin are easier to configure as the lose level is set as a single point (same as setting the spawn point).

**Comment by AlexBartles** [comment]
> Thanks for that. In this version of the plugin, when you select the 2 points for the lose level, they should be be on the same Y level (so you're selecting a 2D rectangle rather than a 3D cuboid). In your config file, the Y coordinate of your 2 lose level points are Y=137 and Y=185 - they should both be the same but the plugin will use the highest which is Y=185.
> 
> The Y coordinate of your spawn point is 154, so when the game starts your players are all below Y=185 (the lose level) so the game ends.
> 
> So either redo the lose level setting both points on the same Y coordinate, or edit the arena config and change the lose level P2 Y value to 137 (or even 138 as the lower bound of the arena is 137, and the lose level should be inside the arena bounds).
> 
> Not sure why the lose level was originally set using 2 points, but the newer versions of the plugin are easier to configure as the lose level is set as a single point (same as setting the spawn point).

Ah. That explains it then. The tutorial I followed (on 1.20.4 and latest version at the time) made it so whatever Y level you were on was the lose level. I'll fix that now and get back to you! Thank you!

**Comment by AlexBartles** [comment]
Yep the game now plays as expected! Thank you again!
