### ISSUE TITLE
Arena could be joined but sign shown as disabled

### ISSUE THREAD

**Issue by LJIT-WD** [steve4744/TNTRun#44]
The arena was shown as disabled on the sign, but I could join the game. I tried to disable it and enable it again, but the sign was still not working normally.

**Comment by LonlyGamerX** [comment]
Does it show any errors in the console/log? are you using bungeecord or a normal server? Did you enter all the info on the sign correctly? Are you using other plugins that mess with signs in any way? Try /tr join and say if any of tnt on the GUI are showing as online or offline or enable or disable

**Comment by steve4744** [comment]
Thanks for reporting this. I've heard of this happening before, but have never been able to recreate it myself.

For the join sign to update correctly, the plugin needs to know its location, which is stored in _signs.yml_. If the location of the sign is lost, then the sign can't be updated, but will still function as a join sign - which is the situation you have. 

Unless you have a backup of _signs.yml_, the only fix is to break the sign and recreate it (only once not every restart!). 
The sign location will be cached until the server shuts down, and then will be written away to _signs.yml_. Every time the server starts it will then be able to read the sign location and update/enable it.

If you know why it happens and can recreate it then that would be useful information to help find a fix. For example, it could be a server 'hang' or using the '/reload' command (which tends to break things) instead of restarting the server properly.

**Comment by LJIT-WD** [comment]
I looked into the signs.yml file and found that it was empty! Luckily, I have a full backup of my server, so I can restore the settings. However, I still do not know why it was empty. I am not sure whether it is a bug of the plugin or an issue of my server.
Now it is working as I restored the settings. Thanks for your help!
