### ISSUE TITLE
Tiny bug and a little fix

### ISSUE THREAD

**Issue by EarlyGamer45** [steve4744/TNTRun#45]
hi
for my server i'm using your tntrun_reloaded plugin, is simple and you can custom everything but i need to report to you some bugs
first in the arenas menù can u fix the player countdown from 0 / 0 to 0/0 (without spaces) and if i reload the plugin with plugman is says the disabled arena message with two prefixed... please fix and i will rate the plugin good.

**Comment by steve4744** [comment]
Thanks for raising the issue. Although technically not a bug, I've added the `{PS}/{MPS}' placeholders to the `menutext` string in `messages.yml`,  so that text can now be configured as required.

The plugin has its own reload commands. The issue with plugman is not an issue with the plugin, but with the way plugman works. It is well known to cause issues with plugins. 

If you need to reload the config or messages then use the `/trsetup reloadconfig` or `/trsetup reloadmsg` commands. Otherwise restart the server in the correct way.
