### ISSUE TITLE
Regeneration problems

### ISSUE THREAD

**Issue by BestMark** [steve4744/TNTRun#56]
Hello,

Sometimes floor blocks do not regen in your plugin. I use legacy version on Paper 1.12.2 server.
![image](https://user-images.githubusercontent.com/18399104/109842553-3c45af00-7c5b-11eb-9ebd-93fcb9b3ab97.png)
![image](https://user-images.githubusercontent.com/18399104/109842566-3f409f80-7c5b-11eb-9291-a922414353be.png)

**Comment by steve4744** [comment]
For the blocks to be missing, the regeneration must have been interrupted for some reason. 

The plugin will only regenerate blocks that are present when the game starts and which are removed during a game. 
So where you have missing blocks like in the pictures, they will have to be repaired manually.
Then after the next game finishes, they will regenerate normally.

**Comment by BestMark** [comment]
It happens all the time. There are holes in the floor after 1-2 days with 15 online on TNTRun.

**Comment by steve4744** [comment]
As I said above, provided the blocks are legitimately broken by players standing on them during a game (and not by any other reason) then they will be regenerated at the end of the game. The break & regen methods have not really changed much in 4-5 years, and are the same methods used in the current 9.9 release. No one else has, or is currently, reporting a problem like this.

So it looks like its something local to your server. If you can provide console logs with some errors that occur at the time the blocks are failing to regenerate, I may be able to diagnose the issue, otherwise I have nothing to work with.

I will keep this issue open for a while in case you can provide some error logs.
Thanks.

**Comment by steve4744** [comment]
Closing as no diagnostic info has been provided.
