### ISSUE TITLE
please add this.

### ISSUE THREAD

**Issue by Aadi-mone** [steve4744/TNTRun#76]
please add a feature like after arena regeneration, there is will be a broadcast, or run a command like **`send @a lobby`**
if that's hard, please add like a broadcast message saying that **`(arena-name) has been regenerated, now u can rejoin`**

regards, 
adarsh a

**Comment by steve4744** [comment]
Thanks for the suggestion but I don't think there is much value in adding this. It literally takes 3 seconds from the time the `commandsonwin` message is broadcast to the arena being ready. A message can be added to the `commandsonwin` list to say the arena is ready, rather than sending 2 messages 3 seconds apart. 

The arena status can be shown with a placeholder, is on the join sign itself and also can be displayed using coloured glass blocks behind the join sign, so there should be no confusion over whether the arena is ready or not.
